# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finance_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyFiUi(object):
    def setupUi(self, PyFiUi):
        PyFiUi.setObjectName("PyFiUi")
        PyFiUi.resize(800, 600)
        self.SingleSecFunctions = QtWidgets.QGroupBox(PyFiUi)
        self.SingleSecFunctions.setGeometry(QtCore.QRect(20, 20, 361, 231))
        self.SingleSecFunctions.setAlignment(QtCore.Qt.AlignCenter)
        self.SingleSecFunctions.setObjectName("SingleSecFunctions")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.SingleSecFunctions)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 40, 141, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SimpleReturn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.SimpleReturn.setObjectName("SimpleReturn")
        self.verticalLayout.addWidget(self.SimpleReturn)
        self.LogReturn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.LogReturn.setObjectName("LogReturn")
        self.verticalLayout.addWidget(self.LogReturn)
        self.SecVol = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.SecVol.setObjectName("SecVol")
        self.verticalLayout.addWidget(self.SecVol)
        self.Securityinput = QtWidgets.QLineEdit(self.SingleSecFunctions)
        self.Securityinput.setGeometry(QtCore.QRect(20, 90, 181, 21))
        self.Securityinput.setObjectName("Securityinput")
        self.Submitsingle = QtWidgets.QPushButton(self.SingleSecFunctions)
        self.Submitsingle.setGeometry(QtCore.QRect(10, 140, 201, 31))
        self.Submitsingle.setObjectName("Submitsingle")

        self.retranslateUi(PyFiUi)
        QtCore.QMetaObject.connectSlotsByName(PyFiUi)

    def retranslateUi(self, PyFiUi):
        _translate = QtCore.QCoreApplication.translate
        PyFiUi.setWindowTitle(_translate("PyFiUi", "PyFi"))
        self.SingleSecFunctions.setTitle(_translate("PyFiUi", "Single Security Functions"))
        self.SimpleReturn.setText(_translate("PyFiUi", "Simple Return"))
        self.LogReturn.setText(_translate("PyFiUi", "Log Return"))
        self.SecVol.setText(_translate("PyFiUi", "Sec Volatility"))
        self.Submitsingle.setText(_translate("PyFiUi", "PushButton"))
