# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finance_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyFiUi(object):
    def setupUi(self, PyFiUi):
        PyFiUi.setObjectName("PyFiUi")
        PyFiUi.resize(800, 600)
        self.SingleSecFunctions = QtWidgets.QGroupBox(PyFiUi)
        self.SingleSecFunctions.setGeometry(QtCore.QRect(20, 20, 361, 231))
        self.SingleSecFunctions.setAlignment(QtCore.Qt.AlignCenter)
        self.SingleSecFunctions.setObjectName("SingleSecFunctions")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.SingleSecFunctions)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 40, 141, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.lineEdit = QtWidgets.QLineEdit(self.SingleSecFunctions)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 181, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.SingleSecFunctions)
        self.pushButton.setGeometry(QtCore.QRect(10, 140, 201, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(PyFiUi)
        QtCore.QMetaObject.connectSlotsByName(PyFiUi)

    def retranslateUi(self, PyFiUi):
        _translate = QtCore.QCoreApplication.translate
        PyFiUi.setWindowTitle(_translate("PyFiUi", "PyFi"))
        self.SingleSecFunctions.setTitle(_translate("PyFiUi", "Single Security Functions"))
        self.radioButton_2.setText(_translate("PyFiUi", "Simple Return"))
        self.radioButton_3.setText(_translate("PyFiUi", "Log Return"))
        self.radioButton.setText(_translate("PyFiUi", "Sec Volatility"))
        self.pushButton.setText(_translate("PyFiUi", "PushButton"))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_PyFiUi()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())